travis:
  secure:
    BINSTAR_TOKEN: CskY4flMpBlAii1ajnFiN5+gQw8sDB70NPz/ZLsrkySZu8k6Nrv6WveFZdHvhZlI/18s3cLmWuKMI2IaCNXYGgW/XYLVsJ9CRUzL4U/GYa0/bEE0P4Uif3tSDvtUJvUmPi5Nta1TijIel/wTI7eifn6iZJH/skkO1Pvns1Eaknwj9Hvk/JkeV5hJPuG9D32s48J8MW003GApG1iK0+0fm15CwJoK6YwW2ARU9Aq+R78vN9/g8HZVb3ZiKRAT2Mwssj438spLKF+oorgupA2KtVU8S4LnEy6ztkh9rmT9Kfm4hbRXKDm1e6Wi+zLKzMxZfYKSJmTitgMj4E/5Neq7kLUKVUzy6FsLlRLrf7pO5v120yimDzy51ZF9jIVkxsLVbUMlMVadhul/BX0SJJZYzMAkv5Vxzc4e8twd6D1n2qJSHrDbs5xk7r7L+HiBz7cqNZOJmvKoTS8IoaTX1hFX/ZSx5shyy1LwezzmrebRPAgOMH+GU8XRPxwPMzX2tcmAjeuHytY/V6XaHZmynpZMMRvT4h8c/h6ESrX8GJfqiiU+cEWMYXpleMycDCaT0w4Ylt3k6jYxFA3ER02OczkL5uhpppCpkJnL3yf2fP4JyA4lRlEoKVzZHKHQt2qL5/8VQp/qi68REfRNucA8fXKy+kVFpdwz8zV5bbXEatpKHdM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
