travis:
  secure:
    BINSTAR_TOKEN: SuG8clVrefqOXZlwp7soMSCeyhMcYYJb3SGQaIkrvxZoadnGAxUSJY5Rj3YzCLyLtkRLKLukpscGpf3yLRftAsGBcLAGwD9w7b8TKmukFmtgbeRkc3GrZ+l7cReY9EUxFuK6LhfV1wM57s9Po+BW7AG8L++N7PSsncqm55Gf+rLtgdCol3+3ysWMeJT+mL4I1p79NfsavjHlEWZiHNvtGvGyuHhVmmpO7RtaDNguXgJ9cL5cxwgLLZ8vr5OWY37O/+LWQvWy67NGelO2nFk0UsBH8eBgp/1Vb5+xPxeRpa7l4vpMo6ngX4Gvnw2yGQ08qpn825yNkIv3rt5Rr2eABAnyziHofmsrNIJAHWvi57Bv62NRNxERSiQmDAZwb4Zjh+77ktI29xMiCbfBiBzOV/a9vpK5dP/wBbz/DTo4qwTbDPTrYPucGpcu217u6qttex1m8oHAsppAGvVuscR1ZdEo9ihLGuqyTwaTqWcPt4oItoM2ia0T4prK6Jhm84s/+MRNYx0+SWE6KPvHsYemf+avLOfGSKxjB8Qw7ZKAsZvU9MF8HFxuHjmOw1g2UlBFOH4CbIHCN/iM/BC1zLaH/NODeCTwezZN8HYvqszlTqdqdGOjnje23+LLsAjdens9WSOUHjsfp6k9G4prmdMCvXiXgS9S+7Ex0GoQLGzCO+M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
